**Basics of NumPy**

In [ ]:
import numpy as np

**Basic of Numpy**

In [ ]:
a = np.array([5,6,7])

In [ ]:
print(a)

[5 6 7]


In [ ]:
b = np.array([[2.0,5.0,6.0],[8.0,2.0,9.0]])

In [ ]:
print(b)

[[2. 5. 6.]
 [8. 2. 9.]]


In [ ]:
#dimentions
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
#shape
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
#type
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
#size
a.itemsize

8

In [ ]:
b.itemsize

8

In [ ]:
a.nbytes

24

**Accessing/Changing specific elements, rows, columns etc.**

In [ ]:
a = np.array([[10,21,22,2,8,9,12],[12,1,2,4,9,6,5]])
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [ ]:
# get specific elements
a[0,3]

2

In [ ]:
a[1,4]

9

In [ ]:
a[0,-1]

12

In [ ]:
a[1,-4]

4

In [ ]:
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [ ]:
print(a[0])

[10 21 22  2  8  9 12]


In [ ]:
print(a[0,:])

[10 21 22  2  8  9 12]


In [ ]:
print(a[:,0])

[10 12]


In [ ]:
#changing the elements

In [ ]:
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [ ]:
a[0,2] = 12

In [ ]:
print(a)

[[10 21 12  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [ ]:
a[:,3] = 3
print(a)

[[10 21 12  3  8  9 12]
 [12  1  2  3  9  6  5]]


In [ ]:
a[:,3] = [1,2]
print(a)

[[10 21 12  1  8  9 12]
 [12  1  2  2  9  6  5]]


In [ ]:
#3d array
b = np.array([[[3,4],[6,5]],[[1,5],[9,8]]])
print(b)

[[[3 4]
  [6 5]]

 [[1 5]
  [9 8]]]


**Initializing Different Arrays**

In [ ]:
#all zeros matrics
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
#numpy.zeros(shape, dtype=float, order='C')
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((4,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [ ]:
np.full((3,3),3,dtype = 'float32')

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [ ]:
a

array([[10, 21, 12,  1,  8,  9, 12],
       [12,  1,  2,  2,  9,  6,  5]])

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#ramdom decimals
np.random.rand(4,2)

array([[0.03645308, 0.78705405],
       [0.48844896, 0.31985018],
       [0.79789135, 0.78294482],
       [0.050479  , 0.79564362]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.66810182, 0.04286826, 0.80662102, 0.06367593, 0.33900996,
        0.99249191, 0.28182805],
       [0.75296279, 0.61781132, 0.06784062, 0.38769982, 0.32090717,
        0.87911674, 0.88696183]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[11,12,5]])
a1 = np.repeat(arr, 3, axis = 1)
print(a1)

[[11 11 11 12 12 12  5  5  5]]


**Mathematics**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a +5 

array([6, 7, 8, 9])

In [ ]:
a - 3

array([-2, -1,  0,  1])

In [ ]:
a*3

array([ 3,  6,  9, 12])

In [ ]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [ ]:
a//3

array([0, 0, 1, 1])

In [ ]:
b = np.array([5,6,7,8])

In [ ]:
a + b

array([ 6,  8, 10, 12])

In [ ]:
a**3

array([ 1,  8, 27, 64])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**

In [ ]:
a = np.full((3,4),5)
b = np.full((4,5),4)
print(a)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [ ]:
a*b

ValueError: ignored

In [ ]:
np.matmul(a,b)

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [ ]:
c = np.identity(5)

In [ ]:
np.linalg.det(c)

1.0

**Statistics**

In [ ]:
s = np.array([[1,2,3],[4,5,6]])

In [ ]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(s, axis = 1)

array([1, 4])

In [ ]:
np.max(s)

6

In [ ]:
np.sum(s)

21

In [ ]:
np.sum(s, axis = 1)

array([ 6, 15])

**Reorganizing Arrays**

In [ ]:
b1 = np.array([[2,4,6,8],[1,3,5,7]])
b1

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [ ]:
a1 = b1.reshape((4,2))

In [ ]:
print(a1)

[[2 4]
 [6 8]
 [1 3]
 [5 7]]


In [ ]:
a1 = b1.reshape((2,3))

ValueError: ignored

In [ ]:
#vertical stacking 
v1 = np.array([2,4,6,8])
v2 = np.array([1,3,4,5])

In [ ]:
np.vstack([v1,v2])

array([[2, 4, 6, 8],
       [1, 3, 4, 5]])

In [ ]:
np.hstack([v1,v2])

array([2, 4, 6, 8, 1, 3, 4, 5])

**Import Data from a file**

In [ ]:
Data = np.genfromtxt('/content/New Text Document.txt', delimiter = ',')

In [ ]:
print(Data)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


**Boolean Masking and Advanced Indexing**

In [ ]:
Data == 2

array([[False,  True, False, False, False],
       [False, False, False, False, False]])

In [ ]:
a = np.array([10,20,30,40,50,60,70,80,90,100])

In [ ]:
a[[2,5,8]]

array([30, 60, 90])

In [ ]:
np.any(a> 50, axis = 0)

True